# Generated by Django 3.2.18 on 2023-04-06 05:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0004_alter_data_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('user', 'name')},
        ),
    ]
