# Generated by Django 3.2.18 on 2023-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_data_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(default='/static/default_image.png', null=True, upload_to='images/'),
        ),
    ]
