# Generated by Django 3.2.18 on 2023-04-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20230411_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
    ]
